name: Build Executable

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            arch: x64
            ext: exe
          - os: macos-latest
            platform: macos
            arch: x64
            ext: app
          - os: macos-14
            platform: macos
            arch: arm64
            ext: app
          - os: ubuntu-latest
            platform: linux
            arch: x64
            ext: 

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        architecture: ${{ matrix.arch }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        pip install imageio

    - name: Build Application
      run: |
        pyinstaller --noconfirm --name=LitematicaViewer --add-data "block:block" --add-data "item:item" --add-data "lang:lang" --add-data "icon.ico:." --add-data "tm_icon.ico:." --windowed --icon="icon.ico" --clean -D script/LitematicaViewer.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: LitematicaViewer-${{ matrix.platform }}-${{ matrix.arch }}
        path: |
          dist/*